// CRITICAL: must be first — patches LitElement before any component is loaded.
import '@lit-labs/ssr-client/lit-element-hydrate-support.js';

// Client runtime: router outlet and link custom elements.
import '@beatzball/litro/runtime/LitroOutlet.js';
import '@beatzball/litro/runtime/LitroLink.js';

// Shoelace is deliberately NOT imported.
//
// The recipe ships eight of its components here, but this site renders none of
// them: there is not one <sl-*> element in any page or component. They still
// cost every visitor about 120KB inside app.js, plus a render-blocking 19KB
// stylesheet in the document head (see src/route-meta.ts), plus 8.5MB of icon
// assets copied into the image.
//
// Add the component import and the theme link back together if a page ever
// wants one, and call setBasePath('/shoelace/') alongside it.

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

// Canonicalise a trailing slash BEFORE the outlet resolves a route.
//
// The generated routes are exact — `/docs/:slug` — so `/docs/getting-started/`
// matched nothing, the page module was never imported, its element was never
// defined, and the `:not(:defined) { visibility: hidden }` rule in
// public/styles/starlight.css (there to stop a flash of undefined elements)
// hid the page for ever. Every docs page was blank at that URL while still
// answering 200 with no console error, no failed request and the entire
// document in the DOM — invisible to a status check, a link checker and
// a post-deploy probe alike.
//
// It is not an exotic URL. nginx serves it happily (`try_files` finds the same
// index.html), `python3 -m http.server` 301-REDIRECTS the clean form to it — so
// every locally previewed docs page was blank — and a reader can simply type
// it.
//
// Fixed here rather than in routes.generated.ts, which is regenerated on every
// build, and rather than in nginx, which would leave dev, preview and any other
// host still broken. `history.replaceState` rewrites the address without a
// navigation or a reload, so the already-served document stays and only the
// path the router reads changes. This runs at module scope, which is before the
// DOMContentLoaded handler below hands the routes to the outlet.
//
// `pathname.length > 1` keeps "/" itself alone, and the greedy `/+$` collapses
// a doubled slash too. The query and hash are carried across deliberately: a
// link to `/docs/setup/#install` must still land on its anchor.
{
  const { pathname, search, hash } = window.location;
  if (pathname.length > 1 && pathname.endsWith('/')) {
    window.history.replaceState(
      window.history.state,
      '',
      pathname.replace(/\/+$/, '') + search + hash,
    );
  }
}

document.addEventListener('DOMContentLoaded', () => {
  const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
  if (outlet) {
    outlet.routes = routes;
  } else {
    console.warn('[litro] <litro-outlet> not found — router will not start.');
  }
});
